// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVfy11cRRBBClvq4jSBTENTFvcZKPuhIw',
    appId: '1:1010797709552:web:24a8884a22397f5d27da35',
    messagingSenderId: '1010797709552',
    projectId: 'blood-don-c808f',
    authDomain: 'blood-don-c808f.firebaseapp.com',
    storageBucket: 'blood-don-c808f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDKlMYeiODRJPGlQoFSqEFT8ci_nCwI40',
    appId: '1:1010797709552:android:b675d3b2b5821e2027da35',
    messagingSenderId: '1010797709552',
    projectId: 'blood-don-c808f',
    storageBucket: 'blood-don-c808f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9wasIpnnkWTt8G5A2wZ5R9c2_2N76Ghw',
    appId: '1:1010797709552:ios:58b28860262d3a6627da35',
    messagingSenderId: '1010797709552',
    projectId: 'blood-don-c808f',
    storageBucket: 'blood-don-c808f.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonat',
  );
}
